services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-service:
    build: ./config-service
    ports:
      - "8889:8889"
    depends_on:
      - discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  keynote-service:
    build: ./keynote-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  conference-service:
    build: ./conference-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - config-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  gateway-service:
    build: ./gateway-service
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
      - config-service
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8889
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  angular-front-app:
    build: ./angular-front-app
    ports:
      - "4200:80"
    depends_on:
      - gateway-service
